<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>5f252a58-304e-475d-8898-c2a9b42e0768</elementGuidId>
    <imagePath></imagePath>
    <name>link_iPhone15Pro</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/ul[1]/li[3]/div[1]/h4[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="products__item in-stock products__item_4-in-row"]:nth-child(3) [class="products__title"] &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/product/apple-iphone-15-pro') and equals(@text,'iPhone 15 Pro')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="iPhone 15 Pro"s] &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/product/apple-iphone-15-pro</value>
        <webElementGuid>f5120a28-365e-41eb-9f7b-9f529ec1dd1d</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>iPhone 15 Pro</value>
        <webElementGuid>f5120a28-365e-41eb-9f7b-9f529ec1dd1d</webElementGuid>
    </webElementProperties>
</WebElementEntity>