<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>54d8b8bb-2864-4380-afb7-dccf2dffd8aa</elementGuidId>
    <imagePath></imagePath>
    <name>link_100012345</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/header[1]/nav[1]/div[1]/div[1]/div[2]/a[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="mars-top-nav__contact"]:nth-child(2) &gt; [class="mars-top-nav__contact-txt"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'+1 (000) 123-45-67')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="+1 (000) 123-45-"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>+1 (000) 123-45-67</value>
        <webElementGuid>3a2297b3-b97a-4806-9880-15d8696d3370</webElementGuid>
    </webElementProperties>
</WebElementEntity>