<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>24ef588f-0a76-4d4f-8a97-6300350c3a95</elementGuidId>
    <imagePath></imagePath>
    <name>link_iPhone15SiliconeCaseWithMagSafe</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[2]/ul[1]/li[2]/div[1]/h4[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="products__item in-stock products__item_3-in-row"]:nth-child(2) [class="products__title"] &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/product/apple-iphone-15-silicone-case-with-magsafe?category=99') and equals(@text,'iPhone 15 Silicone Case with MagSafe')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="iPhone 15 Silicone Case with MagSafe"s]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/product/apple-iphone-15-silicone-case-with-magsafe?category=99</value>
        <webElementGuid>6cc6baaf-08e3-4e00-b6b0-4c3ef9793f30</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>iPhone 15 Silicone Case with MagSafe</value>
        <webElementGuid>6cc6baaf-08e3-4e00-b6b0-4c3ef9793f30</webElementGuid>
    </webElementProperties>
</WebElementEntity>